/* The following code was generated by JFlex 1.4.3 on 10.05.12 17:54 */

/**
* VimScript lexer.
*/

package com.maddyhome.idea.vim.lang.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import static com.maddyhome.idea.vim.lang.lexer.VimScriptTokenTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10.05.12 17:54 from the specification file
 * <tt>D:/CSC/IdeaVIM/ideavim/src/com/maddyhome/idea/vim/lang/lexer/vimscript.flex</tt>
 */
public final class _VimScriptLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\2\0\1\2\22\0\1\3\1\23\1\36\1\50"+
    "\1\17\1\34\1\20\1\35\1\37\1\40\1\31\1\30\1\46\1\10"+
    "\1\13\1\32\1\7\7\12\2\6\1\16\1\45\1\25\1\22\1\24"+
    "\1\47\1\21\4\5\1\14\22\5\1\11\2\5\1\41\1\4\1\42"+
    "\1\33\1\5\1\0\2\15\2\5\1\14\1\5\1\15\4\5\1\15"+
    "\6\5\2\15\1\5\2\15\1\11\2\5\1\43\1\27\1\44\1\26"+
    "\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\2\5\1\6"+
    "\1\7\1\4\1\10\1\1\1\11\1\1\1\12\1\13"+
    "\1\14\1\15\1\1\1\16\1\17\1\20\1\1\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\0\1\5"+
    "\1\37\1\5\1\0\1\40\1\41\1\0\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\0\1\23\1\61"+
    "\1\5\1\62\2\63\2\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[72];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\51\0\122\0\173\0\244\0\315\0\366"+
    "\0\u011f\0\u0148\0\u0171\0\u019a\0\51\0\u01c3\0\u01ec\0\u0215"+
    "\0\u023e\0\u0267\0\u0290\0\u02b9\0\u02e2\0\u030b\0\u0334\0\u035d"+
    "\0\u0386\0\51\0\u03af\0\u03d8\0\51\0\51\0\51\0\51"+
    "\0\51\0\51\0\51\0\51\0\51\0\51\0\51\0\u0401"+
    "\0\u042a\0\u0453\0\u047c\0\u04a5\0\u04ce\0\51\0\51\0\u04f7"+
    "\0\u0520\0\u0549\0\51\0\u0572\0\51\0\51\0\51\0\51"+
    "\0\51\0\51\0\51\0\51\0\51\0\51\0\51\0\u059b"+
    "\0\u05c4\0\u05ed\0\u047c\0\u0616\0\u059b\0\u05c4\0\u063f\0\u0668";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[72];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\7\1\10\1\13\1\7\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\2\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\52\0\1\3\52\0\1\5\45\0\1\47\1\0"+
    "\47\47\5\0\3\7\1\0\2\7\1\0\2\7\40\0"+
    "\1\50\2\10\1\0\1\50\1\10\1\51\2\50\40\0"+
    "\2\50\1\52\1\0\1\53\1\52\1\51\2\50\41\0"+
    "\1\54\1\55\2\0\1\54\7\0\1\56\50\0\1\57"+
    "\33\0\3\7\1\0\2\7\1\0\2\7\1\60\37\0"+
    "\1\61\3\0\1\61\2\0\2\61\40\0\1\62\3\0"+
    "\1\62\2\0\2\62\2\0\1\63\35\0\1\64\3\0"+
    "\1\64\2\0\2\64\55\0\1\65\3\0\1\66\44\0"+
    "\1\67\3\0\1\70\44\0\1\71\50\0\1\72\55\0"+
    "\1\73\27\0\1\54\1\55\2\0\1\54\7\0\1\74"+
    "\50\0\1\75\50\0\1\76\50\0\1\77\26\0\1\100"+
    "\2\0\46\100\1\101\2\0\46\101\5\0\3\50\1\0"+
    "\2\50\1\0\2\50\41\0\2\102\2\0\1\102\43\0"+
    "\2\50\1\52\1\0\1\50\1\52\1\0\2\50\40\0"+
    "\1\50\2\103\1\0\1\50\1\103\1\0\2\50\41\0"+
    "\2\54\2\0\1\54\1\51\50\0\1\51\42\0\1\104"+
    "\3\0\1\104\2\0\2\104\40\0\3\61\1\0\2\61"+
    "\1\0\2\61\40\0\3\62\1\0\2\62\1\0\2\62"+
    "\40\0\3\64\1\0\2\64\1\0\2\64\33\0\1\100"+
    "\2\0\32\100\1\105\13\100\1\101\2\0\33\101\1\106"+
    "\12\101\6\0\2\102\2\0\1\102\1\0\1\107\41\0"+
    "\3\104\1\0\2\104\1\0\2\104\41\0\3\110\1\0"+
    "\1\110\15\0\1\110\26\0\2\110\2\0\1\110\36\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1681];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\11\1\1\11\14\1\1\11\2\1\13\11"+
    "\1\1\1\0\3\1\1\0\2\11\1\0\2\1\1\11"+
    "\1\1\13\11\1\0\10\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[72];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;


  public _VimScriptLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _VimScriptLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 122) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 24: 
          { return LEFT_CURLY_BRACKET;
          }
        case 52: break;
        case 31: 
          { return DICT_KEY_STRING;
          }
        case 53: break;
        case 38: 
          { return OP_EQUAL_TO;
          }
        case 54: break;
        case 26: 
          { return SEMICOLON;
          }
        case 55: break;
        case 21: 
          { return RIGHT_ROUND_BRACKET;
          }
        case 56: break;
        case 29: 
          { return NUMBER_SIGN;
          }
        case 57: break;
        case 5: 
          { return INTEGER;
          }
        case 58: break;
        case 12: 
          { return OP_GT;
          }
        case 59: break;
        case 14: 
          { return OP_PLUS;
          }
        case 60: break;
        case 10: 
          { return OP_ASSIGN;
          }
        case 61: break;
        case 18: 
          { return SINGLE_QUOTE;
          }
        case 62: break;
        case 25: 
          { return RIGHT_CURLY_BRACKET;
          }
        case 63: break;
        case 34: 
          { return ENVIRONMENT_VARIABLE;
          }
        case 64: break;
        case 48: 
          { return OP_CIRCUMFLEX_ASSIGN;
          }
        case 65: break;
        case 32: 
          { return OP_MINUS_ASSIGN;
          }
        case 66: break;
        case 27: 
          { return COMMA;
          }
        case 67: break;
        case 22: 
          { return LEFT_SQUARE_BRACKET;
          }
        case 68: break;
        case 7: 
          { return DOT;
          }
        case 69: break;
        case 19: 
          { return COMMENT;
          }
        case 70: break;
        case 43: 
          { return OP_LT_EQ;
          }
        case 71: break;
        case 15: 
          { return OP_MULT;
          }
        case 72: break;
        case 6: 
          { return OP_MINUS;
          }
        case 73: break;
        case 8: 
          { return COLON;
          }
        case 74: break;
        case 50: 
          { return VARIABLE_WITH_PREFIX;
          }
        case 75: break;
        case 9: 
          { return AMPERSAND;
          }
        case 76: break;
        case 13: 
          { return OP_LT;
          }
        case 77: break;
        case 47: 
          { return OP_DIV_ASSIGN;
          }
        case 78: break;
        case 3: 
          { return WHITESPACE;
          }
        case 79: break;
        case 37: 
          { return REGISTER;
          }
        case 80: break;
        case 23: 
          { return RIGHT_SQUARE_BRACKET;
          }
        case 81: break;
        case 30: 
          { return ESCAPED_CHAR;
          }
        case 82: break;
        case 44: 
          { return OP_LOGICAL_OR;
          }
        case 83: break;
        case 39: 
          { return OP_MATCHES;
          }
        case 84: break;
        case 17: 
          { return OP_MOD;
          }
        case 85: break;
        case 49: 
          { return FLOAT;
          }
        case 86: break;
        case 41: 
          { return OP_NOT_MATCHES;
          }
        case 87: break;
        case 11: 
          { return EXCLAMATION_MARK;
          }
        case 88: break;
        case 40: 
          { return OP_NOT_EQUAL_TO;
          }
        case 89: break;
        case 46: 
          { return OP_MULT_ASSIGN;
          }
        case 90: break;
        case 42: 
          { return OP_GT_EQ;
          }
        case 91: break;
        case 51: 
          { return STRING;
          }
        case 92: break;
        case 35: 
          { return OPTION;
          }
        case 93: break;
        case 16: 
          { return OP_DIV;
          }
        case 94: break;
        case 1: 
          { return BAD_CHARACTER;
          }
        case 95: break;
        case 28: 
          { return QUESTION_MARK;
          }
        case 96: break;
        case 4: 
          { return IDENTIFIER;
          }
        case 97: break;
        case 2: 
          { return NEW_LINE;
          }
        case 98: break;
        case 20: 
          { return LEFT_ROUND_BRACKET;
          }
        case 99: break;
        case 45: 
          { return OP_PLUS_ASSIGN;
          }
        case 100: break;
        case 36: 
          { return OP_LOGICAL_AND;
          }
        case 101: break;
        case 33: 
          { return OP_DOT_ASSIGN;
          }
        case 102: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                return null;
              }
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
